function positions = tbe_pull_end_pos(in1,in2,in3,in4)
%TBE_PULL_END_POS
%    POSITIONS = TBE_PULL_END_POS(IN1,IN2,IN3,IN4)

%    This function was generated by the Symbolic Math Toolbox version 8.5.
%    25-Apr-2020 21:33:55

hip_1 = in2(:,1);
hip_2 = in2(:,2);
hip_3 = in2(:,3);
hip_4 = in2(:,4);
knee_1 = in3(:,1);
knee_2 = in3(:,2);
waist_1 = in1(:,1);
waist_2 = in1(:,2);
x_base = in4(:,1);
y_base = in4(:,2);
z_base = in4(:,3);
t2 = sin(hip_1);
t3 = sin(hip_2);
t4 = -knee_1;
t5 = -knee_2;
t6 = sqrt(2.0);
t7 = pi./4.0;
t8 = hip_1+t4;
t9 = hip_2+t5;
t12 = t7+waist_1;
t13 = t7+waist_2;
t14 = t6.*3.0;
t10 = sin(t8);
t11 = sin(t9);
t15 = -t14;
t16 = cos(t12);
t17 = cos(t13);
t18 = sin(t12);
t19 = sin(t13);
t20 = t15+x_base-3.1e+1./2.0;
positions = reshape([t18.*6.0+x_base+t2.*t18.*2.4e+1-t10.*t18.*2.4e+1+3.1e+1./2.0,t17.*6.0+x_base+t3.*t17.*2.4e+1-t11.*t17.*2.4e+1+3.1e+1./2.0,t20,t20,t16.*-6.0+y_base-t2.*t16.*2.4e+1+t10.*t16.*2.4e+1-3.1e+1./2.0,t19.*6.0+y_base+t3.*t19.*2.4e+1-t11.*t19.*2.4e+1+3.1e+1./2.0,t14+y_base+3.1e+1./2.0,t15+y_base-3.1e+1./2.0,z_base+cos(hip_1).*2.4e+1-cos(t8).*2.4e+1-1.5e+1,z_base+cos(hip_2).*2.4e+1-cos(t9).*2.4e+1-1.5e+1,z_base+cos(hip_3).*4.8e+1-2.1e+1,z_base+cos(hip_4).*4.8e+1-2.1e+1],[4,3]);
