function positions = tbe_walk_end_pos(in1,in2,in3,in4)
%TBE_WALK_END_POS
%    POSITIONS = TBE_WALK_END_POS(IN1,IN2,IN3,IN4)

%    This function was generated by the Symbolic Math Toolbox version 8.5.
%    25-Apr-2020 20:35:29

hip_1 = in2(:,1);
hip_2 = in2(:,2);
hip_3 = in2(:,3);
hip_4 = in2(:,4);
knee_1 = in3(:,1);
knee_2 = in3(:,2);
knee_3 = in3(:,3);
knee_4 = in3(:,4);
waist_1 = in1(:,1);
waist_2 = in1(:,2);
waist_3 = in1(:,3);
waist_4 = in1(:,4);
x_base = in4(:,1);
y_base = in4(:,2);
z_base = in4(:,3);
t2 = sin(hip_1);
t3 = sin(hip_2);
t4 = sin(hip_3);
t5 = sin(hip_4);
t6 = -knee_1;
t7 = -knee_2;
t8 = -knee_3;
t9 = -knee_4;
t10 = pi./4.0;
t11 = hip_1+t6;
t12 = hip_2+t7;
t13 = hip_3+t8;
t14 = hip_4+t9;
t19 = t10+waist_1;
t20 = t10+waist_2;
t21 = t10+waist_3;
t22 = t10+waist_4;
t15 = sin(t11);
t16 = sin(t12);
t17 = sin(t13);
t18 = sin(t14);
t23 = cos(t19);
t24 = cos(t20);
t25 = cos(t21);
t26 = cos(t22);
t27 = sin(t19);
t28 = sin(t20);
t29 = sin(t21);
t30 = sin(t22);
positions = reshape([t27.*6.0+x_base+t2.*t27.*2.4e+1-t15.*t27.*2.4e+1+3.1e+1./2.0,t24.*6.0+x_base+t3.*t24.*2.4e+1-t16.*t24.*2.4e+1+3.1e+1./2.0,t29.*-6.0+x_base-t4.*t29.*2.4e+1+t17.*t29.*2.4e+1-3.1e+1./2.0,t26.*-6.0+x_base-t5.*t26.*2.4e+1+t18.*t26.*2.4e+1-3.1e+1./2.0,t23.*-6.0+y_base-t2.*t23.*2.4e+1+t15.*t23.*2.4e+1-3.1e+1./2.0,t28.*6.0+y_base+t3.*t28.*2.4e+1-t16.*t28.*2.4e+1+3.1e+1./2.0,t25.*6.0+y_base+t4.*t25.*2.4e+1-t17.*t25.*2.4e+1+3.1e+1./2.0,t30.*-6.0+y_base-t5.*t30.*2.4e+1+t18.*t30.*2.4e+1-3.1e+1./2.0,z_base+cos(hip_1).*2.4e+1-cos(t11).*2.4e+1-1.5e+1,z_base+cos(hip_2).*2.4e+1-cos(t12).*2.4e+1-1.5e+1,z_base+cos(hip_3).*2.4e+1-cos(t13).*2.4e+1-1.5e+1,z_base+cos(hip_4).*2.4e+1-cos(t14).*2.4e+1-1.5e+1],[4,3]);
