function positions = tbe_roll_end_pos(in1,in2,in3,in4)
%TBE_ROLL_END_POS
%    POSITIONS = TBE_ROLL_END_POS(IN1,IN2,IN3,IN4)

%    This function was generated by the Symbolic Math Toolbox version 8.5.
%    25-Apr-2020 20:34:42

hip_1 = in2(:,1);
hip_2 = in2(:,2);
hip_3 = in2(:,3);
hip_4 = in2(:,4);
x_base = in4(:,1);
y_base = in4(:,2);
z_base = in4(:,3);
t2 = sqrt(2.0);
t3 = t2.*3.0;
t4 = -t3;
t5 = t3+x_base+3.1e+1./2.0;
t6 = t3+y_base+3.1e+1./2.0;
t7 = t4+x_base-3.1e+1./2.0;
t8 = t4+y_base-3.1e+1./2.0;
positions = reshape([t5,t5,t7,t7,t8,t6,t6,t8,z_base+cos(hip_1).*4.8e+1-2.1e+1,z_base+cos(hip_2).*4.8e+1-2.1e+1,z_base+cos(hip_3).*4.8e+1-2.1e+1,z_base+cos(hip_4).*4.8e+1-2.1e+1],[4,3]);
