function [out1,out2,out3,out4] = tbe_roll_joint_pos(in1,in2,in3,in4)
%TBE_ROLL_JOINT_POS
%    [OUT1,OUT2,OUT3,OUT4] = TBE_ROLL_JOINT_POS(IN1,IN2,IN3,IN4)

%    This function was generated by the Symbolic Math Toolbox version 8.5.
%    25-Apr-2020 20:34:43

hip_1 = in2(:,1);
hip_2 = in2(:,2);
hip_3 = in2(:,3);
hip_4 = in2(:,4);
t2 = cos(hip_1);
t3 = cos(hip_2);
t4 = cos(hip_3);
t5 = cos(hip_4);
t6 = sin(hip_1);
t7 = sin(hip_2);
t8 = sin(hip_3);
t9 = sin(hip_4);
t14 = sqrt(2.0);
t10 = t2.*4.8e+1;
t11 = t3.*4.8e+1;
t12 = t4.*4.8e+1;
t13 = t5.*4.8e+1;
t15 = t14.*3.0;
t17 = t6.*t14.*1.2e+1;
t18 = t7.*t14.*1.2e+1;
t19 = t8.*t14.*1.2e+1;
t20 = t9.*t14.*1.2e+1;
t16 = -t15;
t21 = -t20;
t22 = t15+3.1e+1./2.0;
t23 = t16-3.1e+1./2.0;
out1 = reshape([3.1e+1./2.0,3.1e+1./2.0,t22,t17+t22,t22,t22,-3.1e+1./2.0,-3.1e+1./2.0,t23,-t17+t23,t23,t23,0.0,-1.5e+1,-1.5e+1,t2.*2.4e+1-1.5e+1,t10-1.5e+1,t10-2.1e+1],[6,3]);
if nargout > 1
    t24 = t18+t22;
    out2 = reshape([3.1e+1./2.0,3.1e+1./2.0,t22,t24,t22,t22,3.1e+1./2.0,3.1e+1./2.0,t22,t24,t22,t22,0.0,-1.5e+1,-1.5e+1,t3.*2.4e+1-1.5e+1,t11-1.5e+1,t11-2.1e+1],[6,3]);
end
if nargout > 2
    out3 = reshape([-3.1e+1./2.0,-3.1e+1./2.0,t23,-t19+t23,t23,t23,3.1e+1./2.0,3.1e+1./2.0,t22,t19+t22,t22,t22,0.0,-1.5e+1,-1.5e+1,t4.*2.4e+1-1.5e+1,t12-1.5e+1,t12-2.1e+1],[6,3]);
end
if nargout > 3
    t25 = t21+t23;
    out4 = reshape([-3.1e+1./2.0,-3.1e+1./2.0,t23,t25,t23,t23,-3.1e+1./2.0,-3.1e+1./2.0,t23,t25,t23,t23,0.0,-1.5e+1,-1.5e+1,t5.*2.4e+1-1.5e+1,t13-1.5e+1,t13-2.1e+1],[6,3]);
end
