function rotMatrix = tbe_walk_rot_leg_2(waist_2,hip_2,knee_2)
%TBE_WALK_ROT_LEG_2
%    ROTMATRIX = TBE_WALK_ROT_LEG_2(WAIST_2,HIP_2,KNEE_2)

%    This function was generated by the Symbolic Math Toolbox version 8.5.
%    25-Apr-2020 20:35:29

t2 = -knee_2;
t3 = pi./4.0;
t4 = hip_2+t2;
t6 = t3+waist_2;
t5 = sin(t4);
t7 = cos(t4);
t8 = cos(t6);
t9 = sin(t6);
rotMatrix = reshape([-t5.*t8,-t5.*t9,-t7,t7.*t8,t7.*t9,-t5,t9,-t8,0.0],[3,3]);
