function [out1,out2,out3,out4] = tbe_pull_joint_pos(in1,in2,in3,in4)
%TBE_PULL_JOINT_POS
%    [OUT1,OUT2,OUT3,OUT4] = TBE_PULL_JOINT_POS(IN1,IN2,IN3,IN4)

%    This function was generated by the Symbolic Math Toolbox version 8.5.
%    25-Apr-2020 21:33:58

hip_1 = in2(:,1);
hip_2 = in2(:,2);
hip_3 = in2(:,3);
hip_4 = in2(:,4);
knee_1 = in3(:,1);
knee_2 = in3(:,2);
waist_1 = in1(:,1);
waist_2 = in1(:,2);
t2 = cos(hip_1);
t3 = cos(hip_2);
t4 = cos(hip_3);
t5 = cos(hip_4);
t6 = sin(hip_1);
t7 = sin(hip_2);
t8 = sin(hip_3);
t9 = sin(hip_4);
t10 = -knee_1;
t11 = -knee_2;
t16 = sqrt(2.0);
t17 = pi./4.0;
t12 = t2.*2.4e+1;
t13 = t3.*2.4e+1;
t14 = t4.*4.8e+1;
t15 = t5.*4.8e+1;
t18 = hip_1+t10;
t19 = hip_2+t11;
t22 = t17+waist_1;
t23 = t17+waist_2;
t24 = t16.*3.0;
t34 = t8.*t16.*1.2e+1;
t35 = t9.*t16.*1.2e+1;
t20 = sin(t18);
t21 = sin(t19);
t25 = -t24;
t26 = cos(t22);
t27 = cos(t23);
t28 = sin(t22);
t29 = sin(t23);
t37 = -t35;
t38 = t24+3.1e+1./2.0;
t30 = t26.*6.0;
t31 = t27.*6.0;
t32 = t28.*6.0;
t33 = t29.*6.0;
t39 = t6.*t26.*2.4e+1;
t40 = t7.*t27.*2.4e+1;
t41 = t6.*t28.*2.4e+1;
t42 = t7.*t29.*2.4e+1;
t43 = t25-3.1e+1./2.0;
t36 = -t30;
t44 = -t39;
out1 = reshape([3.1e+1./2.0,3.1e+1./2.0,t32+3.1e+1./2.0,t32+t41+3.1e+1./2.0,t32+t41-t20.*t28.*2.4e+1+3.1e+1./2.0,-3.1e+1./2.0,-3.1e+1./2.0,t36-3.1e+1./2.0,t36+t44-3.1e+1./2.0,t36+t44+t20.*t26.*2.4e+1-3.1e+1./2.0,0.0,-1.5e+1,-1.5e+1,t12-1.5e+1,t12-cos(t18).*2.4e+1-1.5e+1],[5,3]);
if nargout > 1
    out2 = reshape([3.1e+1./2.0,3.1e+1./2.0,t31+3.1e+1./2.0,t31+t40+3.1e+1./2.0,t31+t40-t21.*t27.*2.4e+1+3.1e+1./2.0,3.1e+1./2.0,3.1e+1./2.0,t33+3.1e+1./2.0,t33+t42+3.1e+1./2.0,t33+t42-t21.*t29.*2.4e+1+3.1e+1./2.0,0.0,-1.5e+1,-1.5e+1,t13-1.5e+1,t13-cos(t19).*2.4e+1-1.5e+1],[5,3]);
end
if nargout > 2
    out3 = reshape([-3.1e+1./2.0,-3.1e+1./2.0,t43,-t34+t43,t43,t43,3.1e+1./2.0,3.1e+1./2.0,t38,t34+t38,t38,t38,0.0,-1.5e+1,-1.5e+1,t4.*2.4e+1-1.5e+1,t14-1.5e+1,t14-2.1e+1],[6,3]);
end
if nargout > 3
    t45 = t37+t43;
    out4 = reshape([-3.1e+1./2.0,-3.1e+1./2.0,t43,t45,t43,t43,-3.1e+1./2.0,-3.1e+1./2.0,t43,t45,t43,t43,0.0,-1.5e+1,-1.5e+1,t5.*2.4e+1-1.5e+1,t15-1.5e+1,t15-2.1e+1],[6,3]);
end
