function [out1,out2] = aby_pull_wheels(in1,in2,in3,in4,in5,in6)
%ABY_PULL_WHEELS
%    [OUT1,OUT2] = ABY_PULL_WHEELS(IN1,IN2,IN3,IN4,IN5,IN6)

%    This function was generated by the Symbolic Math Toolbox version 8.5.
%    23-Feb-2021 14:54:56

dot_z_3 = in3(11);
dot_z_4 = in3(12);
dot_beta_3 = in4(7);
dot_beta_4 = in4(8);
dot_alpha_3 = in4(3);
dot_alpha_4 = in4(4);
dot_z_base = in5(:,3);
hip_3 = in1(:,3);
hip_4 = in1(:,4);
steering_3 = in2(:,3);
steering_4 = in2(:,4);
out1 = reshape([sin(hip_3).*-4.8e+1,0.0,0.0,sin(hip_4).*-4.8e+1],[2,2]);
if nargout > 1
    t2 = cos(steering_3);
    t3 = cos(steering_4);
    t4 = sin(steering_3);
    t5 = sin(steering_4);
    t6 = -dot_z_base;
    t7 = sqrt(2.0);
    out2 = [dot_z_3+t6+dot_beta_3.*(t2.*6.0+t2.*t7.*(3.1e+1./2.0))+dot_alpha_3.*(t4.*6.0+t4.*t7.*(3.1e+1./2.0));dot_z_4+t6+dot_beta_4.*(t3.*6.0+t3.*t7.*(3.1e+1./2.0))+dot_alpha_4.*(t5.*6.0+t5.*t7.*(3.1e+1./2.0))];
end
