function [out1,out2] = aby_roll_wheels(in1,in2,in3,in4,in5,in6)
%ABY_ROLL_WHEELS
%    [OUT1,OUT2] = ABY_ROLL_WHEELS(IN1,IN2,IN3,IN4,IN5,IN6)

%    This function was generated by the Symbolic Math Toolbox version 8.5.
%    27-May-2021 14:12:07

dot_z_1 = in3(9);
dot_z_2 = in3(10);
dot_z_3 = in3(11);
dot_z_4 = in3(12);
dot_beta_1 = in4(5);
dot_beta_2 = in4(6);
dot_beta_3 = in4(7);
dot_beta_4 = in4(8);
dot_alpha_1 = in4(1);
dot_alpha_2 = in4(2);
dot_alpha_3 = in4(3);
dot_alpha_4 = in4(4);
dot_z_base = in5(:,3);
hip_1 = in1(:,1);
hip_2 = in1(:,2);
hip_3 = in1(:,3);
hip_4 = in1(:,4);
steering_1 = in2(:,1);
steering_2 = in2(:,2);
steering_3 = in2(:,3);
steering_4 = in2(:,4);
out1 = reshape([sin(hip_1).*-4.8e+1,0.0,0.0,0.0,0.0,sin(hip_2).*-4.8e+1,0.0,0.0,0.0,0.0,sin(hip_3).*-4.8e+1,0.0,0.0,0.0,0.0,sin(hip_4).*-4.8e+1],[4,4]);
if nargout > 1
    t2 = cos(steering_1);
    t3 = cos(steering_2);
    t4 = cos(steering_3);
    t5 = cos(steering_4);
    t6 = sin(steering_1);
    t7 = sin(steering_2);
    t8 = sin(steering_3);
    t9 = sin(steering_4);
    t10 = -dot_z_base;
    t11 = sqrt(2.0);
    out2 = [dot_z_1+t10+dot_beta_1.*(t2.*6.0+t2.*t11.*(3.1e+1./2.0))+dot_alpha_1.*(t6.*6.0+t6.*t11.*(3.1e+1./2.0));dot_z_2+t10+dot_beta_2.*(t3.*6.0+t3.*t11.*(3.1e+1./2.0))+dot_alpha_2.*(t7.*6.0+t7.*t11.*(3.1e+1./2.0));dot_z_3+t10+dot_beta_3.*(t4.*6.0+t4.*t11.*(3.1e+1./2.0))+dot_alpha_3.*(t8.*6.0+t8.*t11.*(3.1e+1./2.0));dot_z_4+t10+dot_beta_4.*(t5.*6.0+t5.*t11.*(3.1e+1./2.0))+dot_alpha_4.*(t9.*6.0+t9.*t11.*(3.1e+1./2.0))];
end
