function rotMatrix = tbe_walk_rot_leg_1(waist_1,hip_1,knee_1)
%TBE_WALK_ROT_LEG_1
%    ROTMATRIX = TBE_WALK_ROT_LEG_1(WAIST_1,HIP_1,KNEE_1)

%    This function was generated by the Symbolic Math Toolbox version 8.5.
%    23-Feb-2021 14:54:28

t2 = -knee_1;
t3 = pi./4.0;
t4 = hip_1+t2;
t6 = t3+waist_1;
t5 = sin(t4);
t7 = cos(t4);
t8 = cos(t6);
t9 = sin(t6);
rotMatrix = reshape([-t5.*t9,t5.*t8,-t7,t7.*t9,-t7.*t8,-t5,-t8,-t9,0.0],[3,3]);
